# Generated by Django 4.2.2 on 2023-06-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='name',
            new_name='instance_id',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='description',
        ),
    ]
